version: 2.1

references:
  workspace_root: &workspace_root
    ~/project
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

executors:
  docker-build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project

jobs:
  prepare:
    steps:
      - checkout
      - run: |
          if [ -z $RELEASE_TOKEN ]; then
            wget -q $(wget -q https://api.github.com/repos/giantswarm/architect/releases/tags/v1.0.0 && cat latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
          else
            wget -q $(wget -q --header "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/tags/v1.0.0 && cat latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
          fi
          chmod +x ./architect
          ./architect version
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - architect
  build:
    executor: docker-build
    steps:
      - checkout
      - setup_remote_docker
      - *attach_workspace
      - run: ./architect --organisation=giantswarm --project=docker-scratch build
  push-master:
    executor: docker-build
    steps:
      - setup_remote_docker
      - *attach_workspace
      - run: ./architect --organisation=giantswarm --project=docker-scratch build

workflows:
  version: 2
  build-master:
    jobs:
      - prepare:
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
      - prepare:
          filters:
            tags:
              only: /^v.*/
      - push-master:
          requires:
            - build
            - prepare
          filters:
            tags:
              only: /^v.*/
